arrowParens: 'avoid'
singleQuote: true
bracketSpacing: true
endOfLine: 'lf'
semi: false
tabWidth: 2
trailingComma: 'none'
plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
